## The makeCacheMatrix creates a matrix that can cache its inverse
## then cacheSolve computes for the inverse of the matrix
## generated by makeCacheMatrix. Supposing the inverse was already
## computed, cacheSolve gets the cached data instead of computing
## for the inverse all over again.

## makeCacheMatrix sets and gets the value of the matrix,
## and sets and gets the matrix's inverse
makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) m <<- solve
  getinverse <- function() m
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}


## cacheSolve checks whether the inverse of the matrix has 
## already been solved and if not, solves for the inverse
cacheSolve <- function(x, ...) {
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
}